// ── Enums ─────────────────────────────────────────────────────────────────────

export type Role = "ADMIN" | "BD_MANAGER" | "PRE_SALES" | "PROPOSAL_WRITER" | "REVIEWER" | "READ_ONLY";

export type RFPStatus =
  | "UPLOADED"
  | "ANALYZING"
  | "DECISION_READY"
  | "ACTION_REQUIRED"
  | "DRAFTING"
  | "IN_REVIEW"
  | "SUBMITTED"
  | "WON"
  | "LOST"
  | "ARCHIVED";

export type DecisionType = "GO" | "NO_GO" | "REVIEW";
export type FlagType = "RED" | "GREEN";
export type FlagSeverity = "CRITICAL" | "MAJOR" | "MINOR";
export type DocType = "PAST_PROPOSAL" | "CAPABILITY" | "CASE_STUDY" | "TEMPLATE" | "COMPLIANCE" | "OTHER";
export type ProposalStatus = "DRAFTING" | "IN_REVIEW" | "APPROVED" | "EXPORTED";
export type ProposalOutcome = "PENDING" | "WON" | "LOST" | "WITHDRAWN";

// ── Core Entities ─────────────────────────────────────────────────────────────

export interface User {
  id: string;
  email: string;
  name: string;
  title: string | null;
  phone: string | null;
  role: Role;
  isActive: boolean;
  mfaEnabled: boolean;
  avatarUrl: string | null;
  preferredLanguage: string;
  preferredTimezone: string;
  createdAt: string;
  lastActiveAt: string | null;
}

export interface RFP {
  id: string;
  titleAr: string | null;
  titleEn: string | null;
  agency: string | null;
  tenderNumber: string | null;
  language: "AR" | "EN" | "MIXED";
  status: RFPStatus;
  deadline: string | null;
  estimatedValueSar: number | null;
  ownerId: string;
  fileCount: number;
  totalPages: number;
  ocrConfidence: number | null;
  createdAt: string;
  updatedAt: string;
  fitScore?: number | null;
  files?: RFPFile[];
}

export interface RFPFile {
  id: string;
  filename: string;
  fileType: "MAIN" | "ANNEX" | "CONTRACT" | "PRICING" | "OTHER";
  sizeBytes: number;
  pageCount: number;
  isOcrRequired: boolean;
  ocrConfidence: number | null;
  status: string;
}

export interface Flag {
  id: string;
  flagType: FlagType;
  severity: FlagSeverity | null;
  flagCode: string | null;
  titleAr: string | null;
  titleEn: string | null;
  descriptionAr: string | null;
  descriptionEn: string | null;
  pageNumber: number | null;
  sectionName: string | null;
  evidenceQuote: string | null;
  isManual: boolean;
}

export interface ScoreBreakdown {
  technicalFit: number;
  businessFit: number;
  riskPenalty: number;
  capabilityMatch: number;
  pastSimilarity: number;
  techStack: number;
  certifications: number;
  projectValue: number;
  strategicAccount: number;
  margin: number;
  salesCycle: number;
  complianceRisk: number;
  deliveryRisk: number;
  financialRisk: number;
  competitionRisk: number;
}

export interface Decision {
  id: string;
  rfpId: string;
  decisionType: DecisionType;
  totalScore: number;
  breakdown: ScoreBreakdown;
  confidence: number;
  explanationAr: string | null;
  explanationEn: string | null;
  redFlags: Flag[];
  greenFlags: Flag[];
  sectionsNeedingReview: string[];
  isOverridden: boolean;
  originalDecisionType: string | null;
  overrideReason: string | null;
  overrideAt: string | null;
  modelVersion: string | null;
  createdAt: string;
}

export interface CitationRef {
  sourceId: string;
  sourceType: string;
  sourceTitle: string;
  chunkText: string;
  pageNumber: number | null;
}

export interface ProposalSection {
  id: string;
  orderIndex: number;
  titleAr: string | null;
  titleEn: string | null;
  contentAr: string | null;
  contentEn: string | null;
  isAiGenerated: boolean;
  isLocked: boolean;
  confidence: number | null;
  hasUngroundedClaims: boolean;
  citations: CitationRef[];
  wordCount: number;
}

export interface Proposal {
  id: string;
  rfpId: string;
  templateId: string | null;
  status: ProposalStatus;
  currentVersion: number;
  approvedBy: string | null;
  approvedAt: string | null;
  submittedAt: string | null;
  outcome: ProposalOutcome;
  createdAt: string;
  updatedAt: string;
  sections: ProposalSection[];
}

export interface KnowledgeDoc {
  id: string;
  title: string;
  docType: DocType;
  language: string;
  year: number | null;
  tags: string[];
  isIndexed: boolean;
  embeddingModel: string | null;
  indexedAt: string | null;
  lastUsedAt: string | null;
  usedCount: number;
  outcome: string;
  sizeBytes: number;
  createdAt: string;
}

export interface Template {
  id: string;
  nameAr: string;
  nameEn: string;
  descriptionEn: string | null;
  supportedLanguages: string;
  usedCount: number;
  winCount: number;
  winRate: number;
  version: number;
  isArchived: boolean;
  sections: TemplateSection[];
}

export interface TemplateSection {
  id: string;
  orderIndex: number;
  titleAr: string;
  titleEn: string;
  descriptionEn: string | null;
  aiInstructions: string | null;
  isAutoGenerated: boolean;
  isRequiredCitations: boolean;
  wordCountTarget: number | null;
}

export interface Notification {
  id: string;
  type: string;
  titleAr: string | null;
  titleEn: string | null;
  bodyAr: string | null;
  bodyEn: string | null;
  deepLink: string | null;
  isRead: boolean;
  createdAt: string;
}

export interface AuditLog {
  id: string;
  userId: string | null;
  action: string;
  targetType: string | null;
  targetId: string | null;
  oldValue: string | null;
  newValue: string | null;
  ipAddress: string | null;
  createdAt: string;
}

// ── API Response Types ────────────────────────────────────────────────────────

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface ApiError {
  detail: string;
  detailAr?: string;
  code?: string;
}

// ── Analytics ─────────────────────────────────────────────────────────────────

export interface KPIs {
  periodDays: number;
  pipeline: { active: number };
  decisions: { total: number; go: number; noGo: number; review: number };
  outcomes: { won: number; lost: number; winRate: number };
}

export interface ChartDataPoint {
  name: string;
  value: number;
  [key: string]: string | number;
}
